pipeline{
  agent any
  
    stages{
      
      stage("Git Checkout"){
        steps{
              git branch: 'main', credentialsId: 'GitID', url: 'https://github.com/shreemansandeep/sampldock.git'
        }
      }
      
      stage("Docker Image Build"){
            steps{
                  sh 'cd sampldock && docker image build -t $JOB_NAME:v1.$BUILD_ID .'
                  sh 'docker image tag $JOB_NAME:v1.$BUILD_ID dockersandheep/$JOB_NAME:v1.$BUILD_ID'
            }
            }
      
      stage('Push image to Docker Hub'){
            steps{
                  withCredentials([string(credentialsId: 'DockerHpwd', variable: 'DockerHubPwd')]) {
                  sh 'docker login -u dockersandheep -p ${DockerHubPwd}'
                  sh 'docker push dockersandheep/$JOB_NAME:v1.$BUILD_ID'
            }   
            }
            }
            
       stage("Docker Container Run"){
            steps{
                  sh 'docker run -itd -p 80:80 dockersandheep/$JOB_NAME:v1.$BUILD_ID'
            }
            }
      
      stage("Running Multi Containers"){
            steps{
                  sh 'cd sampldock && docker-compose up -d'
            }
            }
      
    }
}
